version: '3.8'

services:
  ornelbot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
      - GROQ_API_KEY=${GROQ_API_KEY}  # à définir dans un fichier .env
    volumes:
      - .:/app
