name: Python App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Export Twilio ENV vars
      run: |
        echo "TWILIO_SID=${{ secrets.TWILIO_SID }}" >> $GITHUB_ENV
        echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> $GITHUB_ENV
        echo "TWILIO_WHATSAPP_NUMBER=${{ secrets.TWILIO_WHATSAPP_NUMBER }}" >> $GITHUB_ENV
        echo "RECIPIENT_WHATSAPP_NUMBER=${{ secrets.RECIPIENT_WHATSAPP_NUMBER }}" >> $GITHUB_ENV

    - name: Run Streamlit version check
      run: streamlit --version

    - name: Test notification (facultatif)
      run: |
        echo " Simulation notification Twilio si utilisée à l'import (notify_once)"
